spring.application.name=social-network-backend
spring.config.import=optional:classpath:application-local.properties
spring.security.oauth2.client.registration.google.scope=openid,profile,email
spring.datasource.url=jdbc:postgresql://localhost:5432/socialnetwork
spring.datasource.username=postgres
spring.datasource.password=123456

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

app.frontend.url=${APP_FRONTEND_URL:http://localhost:5173}

app.jwt.secret=ThisIsADemoSecretKeyChangeInProd1234
app.jwt.access-token-expiry-ms=60000
app.jwt.refresh-token-expiry-days=600000
